apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team03-preprod"
  title: "simplenodeservice-team03-preprod"
  description: "Template for the simplenodeservice owned and operated by team03 in environment preprod"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team03-preprod'
    argocd/app-name: simplenodeservice-team03-preprod
  links:
    - url: https://github.com/henrikrexed/platform-engineering-demo.git
      title: Github Repo
      icon: github
    - url: https://shiny-space-memory-rx5rv7v6q7w3p59w-80.app.github.dev/simplenodeservice-team03-preprod
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://shiny-space-memory-rx5rv7v6q7w3p59w-30100.app.github.dev/applications/argocd/simplenodeservice-team03-preprod
    - title: View in Dynatrace
      icon: catalog
      url: https://dsf57140.sprint.apps.dynatracelabs.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team03
  lifecycle: preprod
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team03
  description: Group for application team team03
spec:
  type: business-unit
  profile:
    displayName: Team 03
    email: team03@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]